import type { EumDatabase } from "./schema";
import { DEMO_MASTER_ID, DEMO_STUDENT_ID } from "./schema";

export const SEED_DB: EumDatabase = {
  students: [{ id: DEMO_STUDENT_ID, name: "김지민", points: 1200 }],
  masters: [
    {
      id: DEMO_MASTER_ID,
      name: "김뮤직",
      title: "김뮤직 마스터",
      avatarUrl:
        "https://ui-avatars.com/api/?name=김뮤&background=f3f4f6&color=111827&font-size=0.4",
      heroImageUrl:
        "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=600&auto=format&fit=crop",
      rating: 4.9,
      reviewCount: 312,
      feedbackCount: 842,
      responseTimeLabel: "30분",
      tags: ["팝보컬", "뮤지컬", "입시전문"],
      bio: "정확한 진단이 빠른 성장을 만듭니다.\n불필요한 힘을 빼고 본인만의 톤을 찾을 수 있도록\n책임지고 코칭해드리겠습니다.",
      rankLabel: "eum 추천순위 1위",
      phoneNumber: "010-1234-5678",
      career: [
        "前 JYP Entertainment 보컬 트레이너",
        "실용음악과 외래교수 (○○예술대학교)",
        "뮤지컬 《레미제라블》 보컬 디렉터",
        "누적 1:1 코칭 842건",
      ],
      pricing: {
        feedbackPrice: 69000,
        phonePrice15Min: 18000,
        phonePrice30Min: 30000,
        visitPrice: 80000,
        visitDurationMin: 60,
        feedbackIncludedMin: 5,
        feedbackExtraPer5Min: 2000,
        updatedAt: new Date().toISOString(),
      },
    },
    {
      id: "master-2",
      name: "박소울",
      title: "박소울 마스터",
      avatarUrl:
        "https://ui-avatars.com/api/?name=박소&background=f3f4f6&color=111827&font-size=0.4",
      heroImageUrl:
        "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?q=80&w=600&auto=format&fit=crop",
      rating: 4.8,
      reviewCount: 197,
      feedbackCount: 520,
      responseTimeLabel: "1시간",
      tags: ["R&B", "랩메이킹"],
      phoneNumber: "010-9876-5432",
      bio: "감성 보컬과 랩 플로우를 함께 잡아드려요.\n무대 경험을 바탕으로 실전 감각을 키워드립니다.",
      career: [
        "現 인디 레이블 보컬 디렉터",
        "R&B 보컬 워크숍 강사",
        "누적 1:1 코칭 520건",
      ],
      pricing: {
        feedbackPrice: 25000,
        phonePrice15Min: 20000,
        phonePrice30Min: 35000,
        visitPrice: 90000,
        visitDurationMin: 60,
        feedbackIncludedMin: 5,
        feedbackExtraPer5Min: 2000,
        updatedAt: new Date().toISOString(),
      },
    },
  ],
  feedbackOrders: [
    {
      id: "order-demo-completed",
      studentId: DEMO_STUDENT_ID,
      masterId: DEMO_MASTER_ID,
      status: "completed",
      priceAtPurchase: 69000,
      studentMessage:
        "고음역대 진입할 때 쪼이는 느낌이 아직 나는데 확인 부탁드려요!",
      mediaLabel: "밤양갱 1절",
      mediaType: "audio",
      timestampComments: [
        { time: 12, text: "인트로 — 후두가 살짝 올라가 있어요. 턱 힘 빼고 시작해 보세요." },
        { time: 45, text: "고음 진입 — 배 압력이 풀리면서 목을 쥐어짜요. 복압 유지!" },
        { time: 72, text: "후렴 — 톤이 안정적이에요. 이 느낌 그대로 유지하세요 👍" },
      ],
      masterSummary:
        "녹음본 잘 들었습니다. 확실히 지난번보다 목이 열려있는 소리가 나네요. (진행도 +20%!)",
      createdAt: "2026-08-28T05:30:00.000Z",
      paidAt: "2026-08-28T05:31:00.000Z",
      completedAt: "2026-08-28T06:15:00.000Z",
    },
    {
      id: "order-pending",
      studentId: DEMO_STUDENT_ID,
      masterId: "master-2",
      status: "paid",
      priceAtPurchase: 25000,
      studentMessage: "고음 진입 시 목이 조이는 느낌 점검 부탁드려요.",
      mediaLabel: "고음 발성 교정 피드백",
      mediaType: "audio",
      timestampComments: [],
      createdAt: "2026-08-28T08:00:00.000Z",
      paidAt: "2026-08-28T08:01:00.000Z",
    },
  ],
  reservations: [
    {
      id: "res-upcoming",
      studentId: DEMO_STUDENT_ID,
      masterId: DEMO_MASTER_ID,
      type: "phone",
      status: "scheduled",
      priceAtPurchase: 30000,
      durationMin: 30,
      scheduledAt: "2026-08-28T10:00:00.000Z",
      preQuestion: "고음에서 목이 조이는 느낌이 듭니다.",
      createdAt: "2026-08-27T12:00:00.000Z",
    },
  ],
  favoriteMasterIds: [DEMO_MASTER_ID, "master-2"],
  favoriteAcademyIds: ["haneum-gangnam"],
  studentReviews: [
    {
      id: "review-1",
      studentId: DEMO_STUDENT_ID,
      masterId: DEMO_MASTER_ID,
      productLabel: "음성/영상 피드백",
      rating: 5,
      text: "고음 구간 피드백이 정말 정확했어요. 연습 방향이 확실해졌습니다!",
      createdAt: "2026-08-22T14:30:00.000Z",
    },
    {
      id: "review-2",
      studentId: DEMO_STUDENT_ID,
      masterId: "master-2",
      productLabel: "음성/영상 피드백",
      rating: 4.5,
      text: "랩 플로우 코멘트가 실전에 바로 도움됐어요. 다음에 또 받을게요.",
      createdAt: "2026-08-15T09:00:00.000Z",
    },
  ],
  practiceRecords: [],
};
